توضیحات بخش ۲ و ۳

سینا کاظمی ۹۶۱۰۶۰۱۱

نیما جمالی ۹۶۱۰۵۶۶۱

سپهر فعلی ۹۶۱۰۵۹۵۹

In [ ]:
!apt install chromium-chromedriver
!pip install selenium
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import time
chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('--user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) ' + 'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"')
driver = webdriver.Chrome(chrome_options=chrome_options)


urls = [
    'https://academic.microsoft.com/paper/2981549002',
    'https://academic.microsoft.com/paper/3105081694',
    'https://academic.microsoft.com/paper/2950893734'
]
papers = []
papers_id = []
do_I_array = []

class Paper:
    def __init__(self,identifier):
        self.identifier = identifier
        self.title = None
        self.abstract = None
        self.date = None
        self.authors = []
        self.references = []

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra
Suggested packages:
  webaccounts-chromium-extension unity-chromium-extension adobe-flashplugin
The following NEW packages will be installed:
  chromium-browser chromium-browser-l10n chromium-chromedriver
  chromium-codecs-ffmpeg-extra
0 upgraded, 4 newly installed, 0 to remove and 15 not upgraded.
Need to get 81.0 MB of archives.
After this operation, 273 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 chromium-codecs-ffmpeg-extra amd64 87.0.4280.66-0ubuntu0.18.04.1 [1,122 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 chromium-browser amd64 87.0.4280.66-0ubuntu0.18.04.1 [71.7 MB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 chromium-browser-l10n all 87.0.428

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DeprecationWarning: use options instead of chrome_options
  # This is added back by InteractiveShellApp.init_path()


<div dir="rtl">
عملیات crawling در این فاز با استفاده از کتابخانه selenium انجام شده است.
آپشن headless گذاشته شده تا بار پردازشی بر روی cpu , gpu کاهش یابد.

در ضمن با تعریف user_agent برای web_driver کروم از بلاک شدن درخواست توسط سایت academia جلوگیری کردیم.


</div>

In [ ]:
import random
def crawl(num_of_doc):
    i = 0
    while i < num_of_doc: 
        print(len(papers))
        url = urls.pop(random.randrange(len(urls)))
        paper_id = (url.split("/"))[4]
        if paper_id in papers_id:
            continue
        else:
            driver.get(url)
            time.sleep(2)
            try:
                do_i = driver.find_element_by_xpath('//*[@id="mainArea"]/router-view/div/div/div/div/a[2]')
                if do_i.text in do_I_array:
                    continue
                else:
                    do_I_array.append(do_i.text)
            except:
                pass
            i += 1
            try:
                papers_id.append(paper_id)
                paper = Paper(paper_id)
                title = driver.find_element_by_xpath('//*[@id="mainArea"]/router-view/div/div/div/div/h1')
                paper.title = title.text
                abstract = driver.find_element_by_xpath('//*[@id="mainArea"]/router-view/div/div/div/div/p')
                paper.abstract = abstract.text
                date = driver.find_element_by_xpath('//*[@id="mainArea"]/router-view/div/div/div/div/a/span[1]')
                paper.date = date.text
                authors = driver.find_element_by_xpath('//*[@id="mainArea"]/router-view/div/div/div/div/ma-author-string-collection/div/div')
                paper.authors = authors.text.split(",")
            except:
                i -= 1
                continue
            for x in range(1,11):
                try:
                    ref = driver.find_element_by_xpath(f'//*[@id="mainArea"]/router-view/router-view/ma-edp-serp/div/div[2]/div/compose/div/div[2]/ma-card[{x}]/div/compose/div/div[1]/a[1]')
                    ref_url = ref.get_attribute("href")
                    urls.append(ref_url)
                    ref_id = (ref_url.split("/"))[4]
                    paper.references.append(ref_id)
                except:
                    break
            papers.append(paper.__dict__)

In [ ]:
<div dir="rtl">
سپس 
</div>

<div dir="rtl">
سپس یک کلاس paper ایجاد کرده تا هر مقاله ی بررسی شده را به عنوان یک آبجکت ایجاد کنیم و بعد از آن آرایه ای از آبجکت هارو با پسوند json. ذخیره سازی کنیم.

ابتدا با url هایی که در فایل start.txt وجود داشتند شروع کردیم و سپس برای کراول کردن هر دفعه یکی از url هایی که درون آرایه url ها وجود داشت را به طور رندوم برداشتیم و در صورت تکراری نبودن مقاله شروع به استخراج اطلاعات نمودیم.

تکراری نبودن مقاله را هم با استفاده از paper_id مقالات که در url آنها آمده است بررسی کردیم و هم با استفاده از do_i که در برخی مقالات وجود داشت و در بعضی از مقالات این فیلد نبود که امکان تکراری اومدن آنها وجود دارد.

ورودی تابع crawl تعداد مقالاتی است که میخواهیم بررسی نماییم.

مشخصاتی که از هر مقاله میخواستیم دریافت نماییم را با استفاده از آدرس xpath فایل html استخراج کردیم.

برای اینکه قواعد اخلاقی در crawling را رعایت کرده باشیم بعد از هر بررسی مقاله ۲ ثانیه صبر می کنیم و سپس به سراغ مقاله بعدی می رویم.


</div>

In [ ]:
crawl(5000)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
31
32
33
34
35
35
35
35
35
36
37
38
39
40
40
41
42
43
44
45
46
47
48
48
49
50
50
50
51
52
53
54
55
55
55
55
55
55
56
56
57
58
59
60
61
61
62
63
64
65
66
66
67
68
69
70
71
71
72
73
74
75
75
75
75
75
76
76
77
78
79
80
81
81
82
82
83
84
85
86
86
87
88
89
90
90
91
92
93
94
94
95
95
95
95
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
109
110
110
111
111
112
112
113
114
115
115
115
115
115
116
117
118
119
120
121
121
122
123
124
125
126
127
128
129
130
131
132
132
132
133
134
135
135
135
135
135
135
135
136
136
137
138
139
139
140
141
142
143
144
145
145
146
146
147
148
148
149
150
151
151
152
153
154
155
155
155
155
155
155
155
155
156
157
158
159
160
161
162
163
164
164
165
166
167
168
169
170
171
171
171
171
171
172
173
174
174
175
175
175
175
176
177
178
178
178
178
178
178
179
179
180
181
182
183
184
185
186
187
188
188
189
190
190
190
190
191
192
193
194
195
195
195
195
195
195
196
197
198
19

In [ ]:
import json
jsonString = json.dumps(papers)
jsonFile = open("data.json", "w")
jsonFile.write(jsonString)
jsonFile.close()

NameError: ignored

<div dir="rtl">
برای سیو کردن آرایه از آبجکت ها تحت فرمت json از کتابخانه json استفاده کردیم.

یک فایل json ساخته می شود که حاوی اطلاعات مقالات کراول شده است.
</div>

In [1]:
import json 

f = open('/content/data.json', "r") 
papers = json.load(f) 
papers

[{'abstract': 'In this paper, we propose the Self-Attention Generative Adversarial Network (SAGAN) which allows attention-driven, long-range dependency modeling for image generation tasks. Traditional convolutional GANs generate high-resolution details as a function of only spatially local points in lower-resolution feature maps. In SAGAN, details can be generated using cues from all feature locations. Moreover, the discriminator can check that highly detailed features in distant portions of the image are consistent with each other. Furthermore, recent work has shown that generator conditioning affects GAN performance. Leveraging this insight, we apply spectral normalization to the GAN generator and find that this improves training dynamics. The proposed SAGAN achieves the state-of-the-art results, boosting the best published Inception score from 36.8 to 52.52 and reducing Frechet Inception distance from 27.62 to 18.65 on the challenging ImageNet dataset. Visualization of the attention

<div dir="rtl">
این قسمت برای لود کردن اطلاعات ذخیره شده است.
</div>

In [2]:
set_of_all_paper = set()
for paper in papers:
  set_of_all_paper.add(paper["identifier"])
list_of_all_paper = list(set_of_all_paper)
size_of_matrix = len(set_of_all_paper)
size_of_matrix


5000

In [3]:
import numpy as np
s = (size_of_matrix,size_of_matrix)
adjacency_matrix = np.zeros(s)

In [4]:
for paper in papers:
  index_of_adj_matrix_i = list_of_all_paper.index(paper["identifier"])
  if len(paper["references"]) != 0:
    arr_of_ref_paper = []
    for ref_paper in paper["references"]:
      if ref_paper in list_of_all_paper:
        arr_of_ref_paper.append(ref_paper)
    if len(arr_of_ref_paper) != 0:
      p = 1/len(arr_of_ref_paper)
      for ref_paper in arr_of_ref_paper:
        index_of_adj_matrix_j = list_of_all_paper.index(ref_paper)
        adjacency_matrix[index_of_adj_matrix_i][index_of_adj_matrix_j] = p
    else:
      p = 1/len(list_of_all_paper)
      for j in range(len(list_of_all_paper)):
        adjacency_matrix[index_of_adj_matrix_i][j] = p
adjacency_matrix.sum(axis=1)

array([1., 1., 1., ..., 1., 1., 1.])

<div dir="rtl">
در قسمت های بالا ابتدا لیست رفرنس های مقالات را به رفرنس های ولید کوتاه می کنیم و سپس ماتریس همسایگی را برای هر مقاله می سازیم.

رفرنس های ولید رفرنس هایی هستند که در مقالات بررسی شده آمده باشند.
اگر یک مقاله ای هیچ رفرنس ولیدی نداشته باشد احتمال خیلی کمی برای رفتن از آن مقاله به همه مقالات ولید در نظر میگیریم.

</div>

In [5]:
def pagerank(M, num_iterations: int = 100, d: float = 0.9):

    N = M.shape[1]
    v = np.random.rand(N, 1)
    v = v / np.linalg.norm(v, 1)
    M_hat = (d * M + (1 - d) / N)
    for i in range(num_iterations):
        v = M_hat @ v
        v = v / np.linalg.norm(v, 1)
    return v

<div dir="rtl">
الگوریتم پیج رنک

reference: https://en.wikipedia.org/wiki/PageRank
</div>

In [6]:
pr = pagerank(adjacency_matrix.T, 100, 0.9)
pr

array([[2.20871213e-04],
       [6.29673494e-04],
       [6.10159046e-05],
       ...,
       [5.03424197e-05],
       [3.69687812e-04],
       [1.22223533e-04]])

<div dir="rtl">
الگوریتم را با ضریب dump_factor=0.9 و تعداد iteration 100 اجرا می کنیم.
</div>

In [7]:
top_ten_score = np.sort(pr,axis=None)[::-1]
for i in range(10):
  print(top_ten_score[i])

0.0077854651865100055
0.007213955672903991
0.006083251382714299
0.004265184368760648
0.0031347575926778844
0.002929801165190786
0.0029232079471596993
0.002808904932552366
0.0027166247610322155
0.0026443049269620936


<div dir="rtl">
۱۰ امتیاز برتر در الگوریتم پیج رنک
</div>

In [8]:
top = np.argsort(pr,axis=None)[::-1]
top

array([ 466, 4197, 2828, ..., 3421, 3205,  902])

In [9]:
count_ref = np.zeros(5000)
for paper in papers:
  for ref_paper in paper["references"]:
    if ref_paper in list_of_all_paper:
      count_ref[list_of_all_paper.index(ref_paper)] += 1
for i in range(20):
  top_id = list_of_all_paper[top[i]]
  for paper in papers:
    if paper["identifier"] == top_id:
      print("title: " + str(paper["title"]))
      print("number of references to it: " + str(int(count_ref[top[i]])))
      print("page rank score: " + str(top_ten_score[i]))
  print()

title: An improved method of testing for evolutionary homology.
number of references to it: 5
page rank score: 0.0077854651865100055

title: RNA CODEWORDS AND PROTEIN SYNTHESIS, VI. ON THE NUCLEOTIDE SEQUENCES OF DEGENERATE CODEWORD SETS FOR ISOLEUCINE, TYROSINE, ASPARAGINE, AND LYSINE.
number of references to it: 1
page rank score: 0.007213955672903991

title: Spherical model of a spin glass
number of references to it: 2
page rank score: 0.006083251382714299

title: The Nature of Statistical Learning Theory
number of references to it: 62
page rank score: 0.004265184368760648

title: Multidimensional scaling by optimizing goodness of fit to a nonmetric hypothesis
number of references to it: 4
page rank score: 0.0031347575926778844

title: Maximum likelihood from incomplete data via the EM algorithm
number of references to it: 80
page rank score: 0.002929801165190786

title: Elements of the Theory of Functions and Functional Analysis
number of references to it: 1
page rank score: 0.0029

<div dir="rtl">
در این قسمت هم ۲۰ مقاله برتر به همراه عنوان و تعداد رفرنس به آنها و امتیاز page_rank آورده شده اند.
</div>