توضیحات بخش ۲ و ۳

سینا کاظمی ۹۶۱۰۶۰۱۱

نیما جمالی ۹۶۱۰۵۶۶۱

سپهر فعلی ۹۶۱۰۵۹۵۹

In [ ]:
!apt install chromium-chromedriver
!pip install selenium
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import time
chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('--user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) ' + 'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"')
driver = webdriver.Chrome(chrome_options=chrome_options)


urls = [
    'https://academic.microsoft.com/paper/2981549002',
    'https://academic.microsoft.com/paper/3105081694',
    'https://academic.microsoft.com/paper/2950893734'
]
papers = []
papers_id = []
do_I_array = []

class Paper:
    def __init__(self,identifier):
        self.identifier = identifier
        self.title = None
        self.abstract = None
        self.date = None
        self.authors = []
        self.references = []

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra
Suggested packages:
  webaccounts-chromium-extension unity-chromium-extension adobe-flashplugin
The following NEW packages will be installed:
  chromium-browser chromium-browser-l10n chromium-chromedriver
  chromium-codecs-ffmpeg-extra
0 upgraded, 4 newly installed, 0 to remove and 15 not upgraded.
Need to get 81.0 MB of archives.
After this operation, 273 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 chromium-codecs-ffmpeg-extra amd64 87.0.4280.66-0ubuntu0.18.04.1 [1,122 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 chromium-browser amd64 87.0.4280.66-0ubuntu0.18.04.1 [71.7 MB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 chromium-browser-l10n all 87.0.428

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: DeprecationWarning: use options instead of chrome_options
  # This is added back by InteractiveShellApp.init_path()


<div dir="rtl">
عملیات crawling در این فاز با استفاده از کتابخانه selenium انجام شده است.
آپشن headless گذاشته شده تا بار پردازشی بر روی cpu , gpu کاهش یابد.

در ضمن با تعریف user_agent برای web_driver کروم از بلاک شدن درخواست توسط سایت academia جلوگیری کردیم.


</div>

In [ ]:
import random
def crawl(num_of_doc):
    i = 0
    while i < num_of_doc: 
        print(len(papers))
        url = urls.pop(random.randrange(len(urls)))
        paper_id = (url.split("/"))[4]
        if paper_id in papers_id:
            continue
        else:
            driver.get(url)
            time.sleep(2)
            try:
                do_i = driver.find_element_by_xpath('//*[@id="mainArea"]/router-view/div/div/div/div/a[2]')
                if do_i.text in do_I_array:
                    continue
                else:
                    do_I_array.append(do_i.text)
            except:
                pass
            i += 1
            try:
                papers_id.append(paper_id)
                paper = Paper(paper_id)
                title = driver.find_element_by_xpath('//*[@id="mainArea"]/router-view/div/div/div/div/h1')
                paper.title = title.text
                abstract = driver.find_element_by_xpath('//*[@id="mainArea"]/router-view/div/div/div/div/p')
                paper.abstract = abstract.text
                date = driver.find_element_by_xpath('//*[@id="mainArea"]/router-view/div/div/div/div/a/span[1]')
                paper.date = date.text
                authors = driver.find_element_by_xpath('//*[@id="mainArea"]/router-view/div/div/div/div/ma-author-string-collection/div/div')
                paper.authors = authors.text.split(",")
            except:
                i -= 1
                continue
            for x in range(1,11):
                try:
                    ref = driver.find_element_by_xpath(f'//*[@id="mainArea"]/router-view/router-view/ma-edp-serp/div/div[2]/div/compose/div/div[2]/ma-card[{x}]/div/compose/div/div[1]/a[1]')
                    ref_url = ref.get_attribute("href")
                    urls.append(ref_url)
                    ref_id = (ref_url.split("/"))[4]
                    paper.references.append(ref_id)
                except:
                    break
            papers.append(paper.__dict__)

In [ ]:
<div dir="rtl">
سپس 
</div>

<div dir="rtl">
سپس یک کلاس paper ایجاد کرده تا هر مقاله ی بررسی شده را به عنوان یک آبجکت ایجاد کنیم و بعد از آن آرایه ای از آبجکت هارو با پسوند json. ذخیره سازی کنیم.

ابتدا با url هایی که در فایل start.txt وجود داشتند شروع کردیم و سپس برای کراول کردن هر دفعه یکی از url هایی که درون آرایه url ها وجود داشت را به طور رندوم برداشتیم و در صورت تکراری نبودن مقاله شروع به استخراج اطلاعات نمودیم.

تکراری نبودن مقاله را هم با استفاده از paper_id مقالات که در url آنها آمده است بررسی کردیم و هم با استفاده از do_i که در برخی مقالات وجود داشت و در بعضی از مقالات این فیلد نبود که امکان تکراری اومدن آنها وجود دارد.

ورودی تابع crawl تعداد مقالاتی است که میخواهیم بررسی نماییم.

مشخصاتی که از هر مقاله میخواستیم دریافت نماییم را با استفاده از آدرس xpath فایل html استخراج کردیم.

برای اینکه قواعد اخلاقی در crawling را رعایت کرده باشیم بعد از هر بررسی مقاله ۲ ثانیه صبر می کنیم و سپس به سراغ مقاله بعدی می رویم.


</div>

In [ ]:
crawl(5000)

Streaming output truncated to the last 5000 lines.
1778
1778
1778
1779
1780
1781
1782
1782
1783
1784
1784
1785
1786
1786
1787
1787
1787
1788
1789
1790
1790
1791
1792
1793
1794
1794
1795
1796
1797
1797
1798
1799
1800
1800
1801
1802
1803
1804
1804
1804
1805
1806
1807
1808
1809
1810
1811
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1820
1820
1820
1820
1820
1821
1822
1823
1824
1824
1824
1825
1825
1826
1827
1828
1829
1830
1831
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1840
1840
1841
1842
1843
1843
1844
1845
1846
1847
1847
1847
1847
1847
1847
1848
1849
1849
1850
1851
1852
1853
1854
1854
1854
1854
1855
1855
1856
1857
1858
1858
1858
1859
1860
1860
1861
1862
1863
1863
1863
1864
1865
1866
1866
1867
1868
1869
1869
1870
1870
1871
1872
1872
1873
1874
1875
1876
1876
1877
1878
1878
1879
1880
1881
1882
1882
1882
1883
1883
1883
1883
1884
1885
1886
1887
1888
1889
1889
1890
1891
1892
1892
1893
1893
1894
1894
1895
1896
1897
1898
1899
1899
1900
1901
1902
1902
1903
1903
1904
1905
1905
1905
1905

In [ ]:
import json
jsonString = json.dumps(papers)
jsonFile = open("data.json", "w")
jsonFile.write(jsonString)
jsonFile.close()

<div dir="rtl">
برای سیو کردن آرایه از آبجکت ها تحت فرمت json از کتابخانه json استفاده کردیم.

یک فایل json ساخته می شود که حاوی اطلاعات مقالات کراول شده است.
</div>

In [ ]:
import json 

f = open('/content/data.json', "r") 
papers = json.load(f) 
papers

[{'abstract': 'In this paper, we propose the Self-Attention Generative Adversarial Network (SAGAN) which allows attention-driven, long-range dependency modeling for image generation tasks. Traditional convolutional GANs generate high-resolution details as a function of only spatially local points in lower-resolution feature maps. In SAGAN, details can be generated using cues from all feature locations. Moreover, the discriminator can check that highly detailed features in distant portions of the image are consistent with each other. Furthermore, recent work has shown that generator conditioning affects GAN performance. Leveraging this insight, we apply spectral normalization to the GAN generator and find that this improves training dynamics. The proposed SAGAN achieves the state-of-the-art results, boosting the best published Inception score from 36.8 to 52.52 and reducing Frechet Inception distance from 27.62 to 18.65 on the challenging ImageNet dataset. Visualization of the attention

<div dir="rtl">
این قسمت برای لود کردن اطلاعات ذخیره شده است.
</div>

In [ ]:
set_of_all_paper = set()
for paper in papers:
  set_of_all_paper.add(paper["identifier"])
list_of_all_paper = list(set_of_all_paper)
size_of_matrix = len(set_of_all_paper)
size_of_matrix


5000

In [ ]:
import numpy as np
s = (size_of_matrix,size_of_matrix)
adjacency_matrix = np.zeros(s)

In [ ]:
for paper in papers:
  index_of_adj_matrix_i = list_of_all_paper.index(paper["identifier"])
  if len(paper["references"]) != 0:
    arr_of_ref_paper = []
    for ref_paper in paper["references"]:
      if ref_paper in list_of_all_paper:
        arr_of_ref_paper.append(ref_paper)
    if len(arr_of_ref_paper) != 0:
      p = 1/len(arr_of_ref_paper)
      for ref_paper in arr_of_ref_paper:
        index_of_adj_matrix_j = list_of_all_paper.index(ref_paper)
        adjacency_matrix[index_of_adj_matrix_i][index_of_adj_matrix_j] = p
    else:
      p = 1/len(list_of_all_paper)
      for j in range(len(list_of_all_paper)):
        adjacency_matrix[index_of_adj_matrix_i][j] = p
adjacency_matrix.sum(axis=1)

array([1., 1., 1., ..., 1., 1., 1.])

<div dir="rtl">
در قسمت های بالا ابتدا لیست رفرنس های مقالات را به رفرنس های ولید کوتاه می کنیم و سپس ماتریس همسایگی را برای هر مقاله می سازیم.

رفرنس های ولید رفرنس هایی هستند که در مقالات بررسی شده آمده باشند.
اگر یک مقاله ای هیچ رفرنس ولیدی نداشته باشد احتمال خیلی کمی برای رفتن از آن مقاله به همه مقالات ولید در نظر میگیریم.

</div>

In [ ]:
def pagerank(M, num_iterations: int = 100, d: float = 0.9):

    N = M.shape[1]
    v = np.random.rand(N, 1)
    v = v / np.linalg.norm(v, 1)
    M_hat = (d * M + (1 - d) / N)
    for i in range(num_iterations):
        v = M_hat @ v
        v = v / np.linalg.norm(v, 1)
    return v

<div dir="rtl">
الگوریتم پیج رنک

reference: https://en.wikipedia.org/wiki/PageRank
</div>

In [ ]:
pr = pagerank(adjacency_matrix.T, 100, 0.9)
pr

array([[5.59229753e-05],
       [3.52014646e-04],
       [1.07253610e-04],
       ...,
       [4.47067566e-05],
       [2.07631377e-04],
       [7.59290033e-04]])

<div dir="rtl">
الگوریتم را با ضریب dump_factor=0.9 و تعداد iteration 100 اجرا می کنیم.
</div>

In [ ]:
top_ten_score = np.sort(pr,axis=None)[::-1]
for i in range(10):
  print(top_ten_score[i])

0.008754560817332125
0.00789117864642011
0.0041627468899100755
0.003991958370139756
0.003796091460487201
0.0032912760993457284
0.0030552708771908986
0.0028612525268537146
0.002720603216990728
0.00261321279074422


<div dir="rtl">
۱۰ امتیاز برتر در الگوریتم پیج رنک
</div>

In [ ]:
top = np.argsort(pr,axis=None)[::-1]
top

array([ 847, 2438, 3939, ...,  917, 3666,  692])

In [ ]:
count_ref = np.zeros(5000)
for paper in papers:
  for ref_paper in paper["references"]:
    if ref_paper in list_of_all_paper:
      count_ref[list_of_all_paper.index(ref_paper)] += 1
for i in range(20):
  top_id = list_of_all_paper[top[i]]
  for paper in papers:
    if paper["identifier"] == top_id:
      print("title: " + str(paper["title"]))
      print("number of references to it: " + str(int(count_ref[top[i]])))
      print("page rank score: " + str(top_ten_score[i]))
  print()

title: Receptive fields, binocular interaction and functional architecture in the cat's visual cortex
number of references to it: 26
page rank score: 0.008754560817332125

title: Single unit activity in lateral geniculate body and optic tract of unrestrained cats.
number of references to it: 3
page rank score: 0.00789117864642011

title: Receptive fields of single neurones in the cat's striate cortex
number of references to it: 6
page rank score: 0.0041627468899100755

title: The Nature of Statistical Learning Theory
number of references to it: 64
page rank score: 0.003991958370139756

title: Maximum likelihood from incomplete data via the EM algorithm
number of references to it: 104
page rank score: 0.003796091460487201

title: Statistical Power Analysis for the Behavioral Sciences
number of references to it: 15
page rank score: 0.0032912760993457284

title: A meta-analytic test of intergroup contact theory.
number of references to it: 1
page rank score: 0.0030552708771908986

title: 

<div dir="rtl">
در این قسمت هم ۲۰ مقاله برتر به همراه عنوان و تعداد رفرنس به آنها و امتیاز page_rank آورده شده اند.
</div>